// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBieiUXo4WM4NVpm2jtcNFnq5eDcb6XVv4',
    appId: '1:318653219223:web:29c24f1d11ebae0e69c4d2',
    messagingSenderId: '318653219223',
    projectId: 'tubitak1005-ec1b1',
    authDomain: 'tubitak1005-ec1b1.firebaseapp.com',
    storageBucket: 'tubitak1005-ec1b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjlzFQ1GQWVIudXDqR86PDhPUYPIHwN-w',
    appId: '1:318653219223:android:8fbd9d02395a150d69c4d2',
    messagingSenderId: '318653219223',
    projectId: 'tubitak1005-ec1b1',
    storageBucket: 'tubitak1005-ec1b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9oMiOspi3tktKFHZKEmXd1YLw2yio6eY',
    appId: '1:318653219223:ios:b92bc9f4bcb01b2569c4d2',
    messagingSenderId: '318653219223',
    projectId: 'tubitak1005-ec1b1',
    storageBucket: 'tubitak1005-ec1b1.appspot.com',
    androidClientId: '318653219223-jomhgtv7amqsvb0ti2k9pl1sa6qa6kcl.apps.googleusercontent.com',
    iosClientId: '318653219223-gslms26rekkogfder1qutlhvgluajgrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9oMiOspi3tktKFHZKEmXd1YLw2yio6eY',
    appId: '1:318653219223:ios:40d22816a02db0e769c4d2',
    messagingSenderId: '318653219223',
    projectId: 'tubitak1005-ec1b1',
    storageBucket: 'tubitak1005-ec1b1.appspot.com',
    androidClientId: '318653219223-jomhgtv7amqsvb0ti2k9pl1sa6qa6kcl.apps.googleusercontent.com',
    iosClientId: '318653219223-4ch66t4krejcssdtvkte686pctr964dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
